### PR TITLE
fix: don't rely on node for search

### PR DESCRIPTION
**Pull request by kopecs**
PR checklist:

- [x] Purpose of the code is [evident to future readers](https://semgrep.dev/docs/contributing/contributing-code/#explaining-code)
- [x] Tests included or PR comment includes a reproducible test plan
- [x] Documentation is up-to-date
- [x] A changelog entry was for any user-facing change
- [x] Change has no security implications (otherwise, ping security team)

If you're unsure about any of this, please see:

- [Contribution guidelines](https://semgrep.dev/docs/contributing/contributing-code)!
- [One of the more specific guides located here](https://semgrep.dev/docs/contributing/contributing/)

### CODE REVIEW

**Comment by kopecs** [comment]
@ajbt200128 Any idea about this CI failure?

**Comment by ajbt200128** [comment]
let's add Dockerfile to https://github.com/semgrep/semgrep-vscode/blob/ae6371a69a1c0b760d19da41aff0559ad06f3640/src/test/suite/basic.test.ts#L27, let's just do it in this PR

**Comment by ajbt200128** [comment]
Test plan?

**Comment by kopecs** [comment]
Other than existing tests, I haven't yet looked through how tests are set up here. Any suggestions? It passes manual testing.

**Comment by kopecs** [comment]
> let's add Dockerfile to
> 
> https://github.com/semgrep/semgrep-vscode/blob/ae6371a69a1c0b760d19da41aff0559ad06f3640/src/test/suite/basic.test.ts#L27

Sorry, not sure I follow why (at all, let alone in this PR).

**Comment by ajbt200128** [comment]
> Sorry, not sure I follow why (at all, let alone in this PR).

that skips the file in the test, will make the test pass

**Comment by ajbt200128** [comment]
> Other than existing tests, I haven't yet looked through how tests are set up here. Any suggestions? It passes manual testing.

That works

**Review by ajbt200128 — APPROVED** [review]

**Pull request merged**
